<a href="https://colab.research.google.com/github/Saifullah785/machine-learning-engineer-roadmap/blob/main/Lecture_74_Naive_Bayes_Classifier/Lecture_74_Naive_Bayes_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
# Import necessary libraries
import numpy as np
import pandas as pd

In [26]:
# Load the dataset
data = pd.read_csv('/content/play_tennis.csv')

In [27]:
# Display the first few rows of the dataframe
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [28]:
# Drop the 'day' column as it is not needed for the analysis
data.drop(columns=['day'],inplace=True)

In [29]:
# Display the dataframe after dropping the 'day' column
data.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [30]:
# Problem 1: Predict whether to play tennis based on given conditions
# Outlool-Sunny, Temp-Hot, Humidity-high, Wind-Weak
# Play or No Play?

In [31]:
# Training and Testing phases for the Naive Bayes model
# Lookup Table(Dictionary)

# Testing

In [32]:
# Calculate prior probabilities for 'Yes' and 'No'
# p(Yes)
# P(NO)

In [33]:
# Count the occurrences of 'Yes' and 'No' in the 'play' column
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [34]:
# Calculate the prior probability of playing tennis (Yes) and not playing (No)
py = 9/14
pn = 5/14

In [35]:
# Print the calculated prior probabilities
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [36]:
# Create a crosstab to show the relationship between 'outlook' and 'play'
# OutLook

pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [37]:
# Calculate conditional probabilities for 'outlook' given 'play' (No and Yes)
pon = 0 # Probability of Overcast given No (no occurrences)
prn = 2/5 # Probability of Rain given No
psn = 3/5 # Probability of Sunny given No


poy = 4/9 # Probability of Overcast given Yes
pry = 3/9 # Probability of Rain given Yes
psy = 2/9 # Probability of Sunny given Yes

In [38]:
# Create a crosstab to show the relationship between 'temp' and 'play'
# OutLook

pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [39]:
# Calculate conditional probabilities for 'temp' given 'play' (No and Yes)
PCoolNo = 1/5
PhotNo = 2/5
PmildNo = 2/5

PCoolYes = 3/9
PhotYes = 2/9
PmildYes = 4/9

In [40]:
# Create a crosstab to show the relationship between 'humidity' and 'play'
# OutLook

pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [41]:
# Calculate conditional probabilities for 'humidity' given 'play' (No and Yes)
pHighNo = 4/5
pNormalNo = 1/5

pHighYes = 3/9
pNormalYes = 6/9

In [42]:
# Create a crosstab to show the relationship between 'wind' and 'play'
# wind

pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [43]:
# Calculate conditional probabilities for 'wind' given 'play' (No and Yes)
PStrongNo = 3/5
PWeakNo = 2/5

PStrongYes = 3/9
PWeakYes = 6/9

In [44]:
# Calculate the probability of 'Yes' given the specific conditions using Naive Bayes formula
# Outlook-Sunny, Temp-Hot, Humidity-High, Wind-Weak

p = py*psy*PhotYes*pHighYes*PWeakYes
print(p)

0.007054673721340388

In [45]:
# Calculate the probability of 'No' given the specific conditions using Naive Bayes formula
Pno = pn*prn*PhotNo*pHighNo*PWeakNo
print(Pno)

0.01828571428571429

In [46]:
# Based on the calculated probabilities, predict 'No Play'
# No Play