<a href="https://colab.research.google.com/github/Saifullah785/machine-learning-engineer-roadmap/blob/main/Lecture_78_Optuna_Basics_yt/Lecture_78_Optuna_Basics_yt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.5.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.16.5)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.43)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.2)
Downloading optuna-4.5.0-py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.9/400.9 kB 8.1 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.9.0 optuna-4.5.0

In [4]:
# import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [5]:
# load the pima indian diabetes dataset from sklearn
# Note: scikit-learn's build-in 'load_diabetes' is a regression dataset.
# we will load the actual diabetes dataset from an external source

import pandas as pd
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

In [6]:
# load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [7]:
import numpy as np

# Replace zero values with NaN is columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

#check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [8]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

#Define the objective function
def objective(trial):
  # Suggest values for the hyperparameters
  n_estimators = trial.suggest_int('n_estimators',  50, 200)
  max_depth = trial.suggest_int('max_depth', 3, 20)

  # create the randomForestClassifier with suggested hyperparameters
  model = RandomForestClassifier(
      n_estimators=n_estimators,
      max_depth=max_depth,
      random_state=42
  )
  # Perform 3-fold cross-validation and calculate accuracy
  score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

  return score

In [10]:
# create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler()) # we aim to maximize accuracy

# RUn 50 trials to find the best hyperparameters
study.optimize(objective, n_trials=50)

[I 2025-09-12 06:27:57,880] A new study created in memory with name: no-name-865c2f04-c90c-4b59-bf34-34328ddbd700
[I 2025-09-12 06:27:58,682] Trial 0 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 63, 'max_depth': 4}. Best is trial 0 with value: 0.7597765363128491.
[I 2025-09-12 06:28:00,225] Trial 1 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 143, 'max_depth': 15}. Best is trial 1 with value: 0.7709497206703911.
[I 2025-09-12 06:28:01,684] Trial 2 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 130, 'max_depth': 6}. Best is trial 1 with value: 0.7709497206703911.
[I 2025-09-12 06:28:03,218] Trial 3 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 145, 'max_depth': 20}. Best is trial 1 with value: 0.7709497206703911.
[I 2025-09-12 06:28:04,245] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 56, 'max_depth': 20}. Best is trial 1 with value: 0.7709497206703911.
[I 2025-09-12 06:28:05,558] Trial 5 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 109, 'max_depth': 7}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:08,085] Trial 6 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 167, 'max_depth': 17}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:09,807] Trial 7 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 129, 'max_depth': 9}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:10,892] Trial 8 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 57, 'max_depth': 17}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:13,251] Trial 9 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 102, 'max_depth': 16}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:15,956] Trial 10 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 199, 'max_depth': 10}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:17,827] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 179, 'max_depth': 13}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:18,861] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 96, 'max_depth': 7}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:19,793] Trial 13 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 162, 'max_depth': 12}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:20,265] Trial 14 finished with value: 0.756052141527002 and parameters: {'n_estimators': 92, 'max_depth': 3}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:20,912] Trial 15 finished with value: 0.7579143389199255 and parameters: {'n_estimators': 109, 'max_depth': 9}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:21,917] Trial 16 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 176, 'max_depth': 14}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:22,801] Trial 17 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 155, 'max_depth': 18}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:23,428] Trial 18 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 117, 'max_depth': 6}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:23,931] Trial 19 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 81, 'max_depth': 11}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:25,528] Trial 20 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 188, 'max_depth': 8}. Best is trial 5 with value: 0.7765363128491621.
[I 2025-09-12 06:28:26,199] Trial 21 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 72, 'max_depth': 17}. Best is trial 21 with value: 0.7783985102420856.
[I 2025-09-12 06:28:26,851] Trial 22 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 77, 'max_depth': 18}. Best is trial 21 with value: 0.7783985102420856.
[I 2025-09-12 06:28:27,286] Trial 23 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 74, 'max_depth': 15}. Best is trial 21 with value: 0.7783985102420856.
[I 2025-09-12 06:28:27,980] Trial 24 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 119, 'max_depth': 19}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:28,683] Trial 25 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 119, 'max_depth': 20}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:29,501] Trial 26 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 139, 'max_depth': 19}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:30,214] Trial 27 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 120, 'max_depth': 19}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:30,739] Trial 28 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 90, 'max_depth': 20}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:31,161] Trial 29 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 70, 'max_depth': 17}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:31,465] Trial 30 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 18}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:31,887] Trial 31 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 72, 'max_depth': 16}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:32,400] Trial 32 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 84, 'max_depth': 16}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:32,792] Trial 33 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 67, 'max_depth': 19}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:33,183] Trial 34 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 63, 'max_depth': 19}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:33,972] Trial 35 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 136, 'max_depth': 20}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:34,834] Trial 36 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 149, 'max_depth': 19}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:35,238] Trial 37 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 65, 'max_depth': 14}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:35,859] Trial 38 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 108, 'max_depth': 18}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:36,575] Trial 39 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 122, 'max_depth': 20}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:37,714] Trial 40 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 128, 'max_depth': 20}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:38,379] Trial 41 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 71, 'max_depth': 17}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:38,926] Trial 42 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 56, 'max_depth': 17}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:39,509] Trial 43 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 66, 'max_depth': 15}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:40,016] Trial 44 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 87, 'max_depth': 19}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:40,322] Trial 45 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 17}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:40,904] Trial 46 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 99, 'max_depth': 16}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:41,583] Trial 47 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 113, 'max_depth': 18}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:42,188] Trial 48 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 103, 'max_depth': 14}. Best is trial 24 with value: 0.7821229050279329.
[I 2025-09-12 06:28:42,864] Trial 49 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 115, 'max_depth': 18}. Best is trial 24 with value: 0.7821229050279329.

In [11]:
# print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7821229050279329
Best hyperparameters: {'n_estimators': 119, 'max_depth': 19}

In [12]:
from sklearn.metrics import accuracy_score

#  Train a RandomForestClassifier using the best hyperparameters from optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# print the test acccuracy

print(f'Test accuracy with best hyperparameters: {test_accuracy:.2f}')

Test accuracy with best hyperparameters: 0.74

## Optuna Visualizations

In [13]:
# For visualizations

from optuna.visualization import plot_optimization_history, \
plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [14]:
# 1. Optimization History
plot_optimization_history(study).show()

In [15]:
# 2. parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [16]:
# 3.Slice Plot
plot_slice(study).show()

In [17]:
# 4. Contour Plot
plot_contour(study).show()

In [18]:
# 5. Parameter Importances Plot
plot_param_importances(study).show()

# Optimizing Mulitple ML Models

In [19]:
# importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [22]:
# Define the objective function for Optuna
def objective(trial):
  # Choose the algorithm to tune
  classifier_name = trial.suggest_categorical('classifier', ['SVM','RandomForest', 'GradientBoosting'])
  if classifier_name == 'SVM':
    # Suggest hyperparameters for SVM
    c = trial.suggest_float('C', 0.1, 100, log =True)
    kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
    gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])
    model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

  elif classifier_name == 'RandomForest':
    # Suggest hyperparameters for RandomForest
    n_estimators = trial.suggest_int('n_estimators', 50, 300)
    max_depth = trial.suggest_int('max_depth', 3, 20)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
    bootstrap = trial.suggest_categorical('bootstrap', [True, False])

    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        bootstrap=bootstrap,
        random_state=42
    )

  elif classifier_name == 'GradientBoosting':
    # Suggest hyperparameters for GradientBoosting
    n_estimators = trial.suggest_int('n_estimators', 50, 300)
    learning_rate = trial.suggest_float('learning_rat', 0.01, 0.3, log=True)
    max_depth = trial.suggest_int('max_depth', 3, 20)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

    model = GradientBoostingClassifier(
        n_estimators=n_estimators,
        learning_rate=learning_rate,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        random_state=42
    )
  # Perform cross-validation and return the mean accuracy
  score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
  return score

In [23]:
# create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2025-09-12 06:30:45,347] A new study created in memory with name: no-name-7cebbe86-1190-4974-9237-48d0e55ccf4e
[I 2025-09-12 06:30:45,385] Trial 0 finished with value: 0.7597765363128491 and parameters: {'classifier': 'SVM', 'C': 6.646123816110229, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 0 with value: 0.7597765363128491.
[I 2025-09-12 06:30:45,417] Trial 1 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.7735524248608444, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:46,692] Trial 2 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 257, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:46,969] Trial 3 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 53, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:51,698] Trial 4 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 295, 'learning_rat': 0.17063274664740466, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:55,157] Trial 5 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 252, 'learning_rat': 0.022946348411111907, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 7}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:56,435] Trial 6 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 246, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:56,465] Trial 7 finished with value: 0.6871508379888268 and parameters: {'classifier': 'SVM', 'C': 11.603742463206638, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:58,121] Trial 8 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 294, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:59,415] Trial 9 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 94, 'learning_rat': 0.04469354079007895, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 6}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:59,447] Trial 10 finished with value: 0.7094972067039106 and parameters: {'classifier': 'SVM', 'C': 0.11762066010350415, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:59,483] Trial 11 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.31476985723821327, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:30:59,792] Trial 12 finished with value: 0.7541899441340782 and parameters: {'classifier': 'RandomForest', 'n_estimators': 56, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 1 with value: 0.7672253258845437.
[I 2025-09-12 06:31:00,421] Trial 13 finished with value: 0.7765363128491619 and parameters: {'classifier': 'RandomForest', 'n_estimators': 145, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 13 with value: 0.7765363128491619.
[I 2025-09-12 06:31:00,454] Trial 14 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.9953742390783178, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7839851024208566.
[I 2025-09-12 06:31:01,117] Trial 15 finished with value: 0.7783985102420856 and parameters: {'classifier': 'RandomForest', 'n_estimators': 150, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 14 with value: 0.7839851024208566.
[I 2025-09-12 06:31:01,565] Trial 16 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 60.37330182928018, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:02,142] Trial 17 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 89.46612661404423, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:02,579] Trial 18 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 66.77361414390164, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:03,308] Trial 19 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 97.50267032585099, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:03,475] Trial 20 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 22.334622441146127, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:03,842] Trial 21 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 82.33713286916257, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:03,992] Trial 22 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 37.008676058327914, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:04,141] Trial 23 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 31.97044268923693, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:04,493] Trial 24 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 96.39540484336777, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:04,571] Trial 25 finished with value: 0.702048417132216 and parameters: {'classifier': 'SVM', 'C': 42.12929382858266, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:07,409] Trial 26 finished with value: 0.7430167597765364 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 198, 'learning_rat': 0.01035302908911959, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:07,444] Trial 27 finished with value: 0.6945996275605214 and parameters: {'classifier': 'SVM', 'C': 10.842948674926099, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:07,550] Trial 28 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 20.433752767304423, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:07,598] Trial 29 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.994493904144414, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:07,784] Trial 30 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 46.61710722131724, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:08,159] Trial 31 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 99.53630784069209, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:08,395] Trial 32 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 61.45197525121031, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:08,621] Trial 33 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 54.54554028179222, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:08,762] Trial 34 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 23.008878799932226, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:08,909] Trial 35 finished with value: 0.6741154562383613 and parameters: {'classifier': 'SVM', 'C': 96.71085727184952, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:11,507] Trial 36 finished with value: 0.7318435754189944 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 189, 'learning_rat': 0.19783532514903548, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 8}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:11,541] Trial 37 finished with value: 0.6927374301675977 and parameters: {'classifier': 'SVM', 'C': 54.517525006722096, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:11,643] Trial 38 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 19.636520400112303, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:13,086] Trial 39 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 108, 'learning_rat': 0.07366619579994482, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:13,169] Trial 40 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 11.963254120505741, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:13,306] Trial 41 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 27.659692009802733, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:13,564] Trial 42 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 61.16406217414533, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:13,879] Trial 43 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 61.74025734446257, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:13,956] Trial 44 finished with value: 0.7355679702048418 and parameters: {'classifier': 'SVM', 'C': 36.7064722865805, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:14,045] Trial 45 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 6.373780260390611, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:15,543] Trial 46 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 219, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:17,789] Trial 47 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 148, 'learning_rat': 0.011867099717722908, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:17,828] Trial 48 finished with value: 0.7728119180633147 and parameters: {'classifier': 'SVM', 'C': 1.9953808082806745, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:18,235] Trial 49 finished with value: 0.7523277467411545 and parameters: {'classifier': 'RandomForest', 'n_estimators': 102, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:18,495] Trial 50 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 70.51707637355395, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:18,959] Trial 51 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 99.18887438778975, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:19,247] Trial 52 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 73.12639238186472, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:19,282] Trial 53 finished with value: 0.6871508379888268 and parameters: {'classifier': 'SVM', 'C': 32.711075927574605, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:19,373] Trial 54 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 13.71560895142646, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:19,453] Trial 55 finished with value: 0.7039106145251397 and parameters: {'classifier': 'SVM', 'C': 40.5790874132925, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:19,897] Trial 56 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 76.36681988712974, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:19,945] Trial 57 finished with value: 0.7188081936685289 and parameters: {'classifier': 'SVM', 'C': 45.80042084353926, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:21,137] Trial 58 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 219, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:22,192] Trial 59 finished with value: 0.7374301675977654 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 124, 'learning_rat': 0.2945856647531005, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 9}. Best is trial 16 with value: 0.7858472998137801.
[I 2025-09-12 06:31:22,223] Trial 60 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17554053303993863, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 60 with value: 0.7877094972067038.
[I 2025-09-12 06:31:22,253] Trial 61 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23600686192855178, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 60 with value: 0.7877094972067038.
[I 2025-09-12 06:31:22,282] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1487410667880136, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,312] Trial 63 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1367026698691512, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,341] Trial 64 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13898136166708, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,369] Trial 65 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1226876477944892, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,400] Trial 66 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11239694333157642, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,432] Trial 67 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1093096740042429, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,464] Trial 68 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1141385271194235, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,497] Trial 69 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17066851296467678, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,532] Trial 70 finished with value: 0.7430167597765364 and parameters: {'classifier': 'SVM', 'C': 0.5030886123553856, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,563] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12178451340246961, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,593] Trial 72 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15167079583859197, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,624] Trial 73 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14688777215645402, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,656] Trial 74 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.30931290314473386, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,701] Trial 75 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.10493310590162029, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:22,733] Trial 76 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21912494921911677, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:23,162] Trial 77 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 76, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:23,194] Trial 78 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1373761673164917, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:23,229] Trial 79 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4090721541288155, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:26,640] Trial 80 finished with value: 0.7355679702048418 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 174, 'learning_rat': 0.0754831565387224, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 62 with value: 0.7895716945996275.
[I 2025-09-12 06:31:26,687] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14138942804209903, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 62 with value: 0.7895716945996275.

In [24]:
# Retrieve the best trial
best_trial = study.best_trial

# Print the best trial's accuracy and hyperparameters
print(f'Best trial accuracy: {best_trial.value}')
print(f'Best hyperparameters: {best_trial.params}')

Best trial accuracy: 0.7895716945996275
Best hyperparameters: {'classifier': 'SVM', 'C': 0.1487410667880136, 'kernel': 'linear', 'gamma': 'scale'}

In [25]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rat,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.759777,2025-09-12 06:30:45.349511,2025-09-12 06:30:45.385290,0 days 00:00:00.035779,6.646124,NaN,SVM,auto,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,0.767225,2025-09-12 06:30:45.386368,2025-09-12 06:30:45.417134,0 days 00:00:00.030766,0.773552,NaN,SVM,scale,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
2,2,0.763501,2025-09-12 06:30:45.418052,2025-09-12 06:30:46.692297,0 days 00:00:01.274245,NaN,False,RandomForest,NaN,NaN,NaN,20.0,2.0,5.0,257.0,COMPLETE
3,3,0.767225,2025-09-12 06:30:46.693663,2025-09-12 06:30:46.969502,0 days 00:00:00.275839,NaN,True,RandomForest,NaN,NaN,NaN,16.0,10.0,9.0,53.0,COMPLETE
4,4,0.741155,2025-09-12 06:30:46.970421,2025-09-12 06:30:51.698354,0 days 00:00:04.727933,NaN,NaN,GradientBoosting,NaN,NaN,0.170633,17.0,2.0,4.0,295.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.783985,2025-09-12 06:31:28.033976,2025-09-12 06:31:28.078552,0 days 00:00:00.044576,0.442434,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.765363,2025-09-12 06:31:28.079714,2025-09-12 06:31:28.146418,0 days 00:00:00.066704,0.249105,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.772812,2025-09-12 06:31:28.147633,2025-09-12 06:31:30.252758,0 days 00:00:02.105125,NaN,False,RandomForest,NaN,NaN,NaN,10.0,8.0,9.0,276.0,COMPLETE
98,98,0.711359,2025-09-12 06:31:30.253695,2025-09-12 06:31:30.301175,0 days 00:00:00.047480,0.124737,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.767225,2025-09-12 06:31:30.302003,2025-09-12 06:31:32.796765,0 days 00:00:02.494762,NaN,NaN,GradientBoosting,NaN,NaN,0.028623,6.0,3.0,3.0,232.0,COMPLETE

In [26]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 78
RandomForest        12
GradientBoosting    10
Name: count, dtype: int64

In [27]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.745624
RandomForest        0.765673
SVM                 0.772334
Name: value, dtype: float64

In [28]:
# 1.Optimization History
plot_optimization_history(study).show()

In [29]:
# 3.Slice plot
plot_slice(study).show()

In [30]:
# 5. hyperparameter importance
plot_param_importances(study).show()